repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v4.4.1
      hooks:
        - id: commitizen
          stages: [commit-msg]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: debug-statements
        - id: detect-private-key
        - id: end-of-file-fixer

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.0
      hooks:
        - id: ruff

    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
        - id: black
