version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    env_file: .env
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
      - media_volume:/code/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh -c 'sleep 10 && certbot certonly --webroot --webroot-path=/code/static -d seusite.com -d www.seusite.com --email seu@email.com --agree-tos --non-interactive'"

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot-etc:
  certbot-var:
