version: '3.9'

services:
  web:
    build: /var/jenkins_home/workspace/website-ci_main
    container_name: django_app
    env_file: .env
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - jenkins-net

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - jenkins-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - jenkins-nginx-conf:/etc/nginx/conf.d
      - static_volume:/code/static
      - media_volume:/code/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/letsencrypt/www:/var/www/certbot:ro
    depends_on:
      - web
    networks:
      - jenkins-net

networks:
  jenkins-net:
    external: true

volumes:
  jenkins-nginx-conf:
    external: true
  postgres_data:
  static_volume:
  media_volume:
