version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    env_file: .env
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/var/lib/letsencrypt
      - static_volume:/code/static
      - media_volume:/code/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./letsencrypt:/var/lib/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
    entrypoint: >
      /bin/sh -c "sleep 10 &&
      certbot certonly --webroot --webroot-path=/code/static
      --email fabricio.alves2698@gmail.com
      --agree-tos --no-eff-email
      -d fabricioalves.engineer"

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot-etc:
  certbot-var:
