version: '3.9'

services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: "${DOCKER_GID}"
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-nginx-conf:/var/jenkins_home/shared/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
  jenkins-nginx-conf:
    driver: local
